
name: caller_2
on:
    workflow_call:
        inputs:
            environment:
               description: 'Environment to run the workflow on'
               required: true
               type: string

jobs:
    caller_2:    
     runs-on: ubuntu-latest
     environment: ${{ github.event.inputs.environment }}

     steps:

        - name: Echo env
          run: |
              echo ${{ github.event.inputs.environment }}
              echo ${{ secrets.ONE }}