
name: test
on:
   workflow_dispatch:    
        inputs:
            environment:
               description: 'Environment to run the workflow on'
               required: true
               default: 'Features'
               type: choice
               options:
                    - 'Features'
                    - 'Development'
            caller_1:
                description: 'Deploy Caller 1'
                required: true
                default: 'true'
                type: choice
                options:
                    - 'true'
                    - 'false'


permissions:
  contents: read
  packages: write

jobs:
   main_job:
    runs-on: ubuntu-latest
    environment: Approval 
    steps:
        - name: Run command with sudo
          run: |
            apt update


   deploy_caller_1:
       if: ${{ github.event.inputs.caller_1 == 'true' }}
       needs: main_job
       uses: ./.github/workflows/caller_1.yml
       with:
         environment: ${{ github.event.inputs.environment }}
       secrets: inherit
    
   deploy_caller_2:
       uses: ./.github/workflows/caller_2.yml
       needs: main_job
       with:
         environment: ${{ github.event.inputs.environment }}
       secrets: inherit

   deploy_caller_3:    
     runs-on: ubuntu-latest
     needs: main_job
     environment: ${{ github.event.inputs.environment }}

     steps:
        - name: Echo env
          run: |
              echo ${{ github.event.inputs.environment }}
              echo ${{ secrets.ONE }}
       
